//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeNCrawLer_0._1._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeNCrawLer_0._1._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; &gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;title&gt;PeNCrawLer - Crawler and DirBuster&lt;/title&gt;
        ///  &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///
        ///
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css&quot;&gt;
        ///
        ///  
        ///      &lt;link rel=&quot;stylesheet&quot; href=&quot;css/style.css&quot;&gt;
        ///
        ///  
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///  &lt;div id=&quot;demo&quot;&gt;
        ///  &lt;h1&gt;PeNCrawLer - Crawler and DirBuster&lt;/h1&gt;
        ///  &lt;h2&gt;Table of txtTitl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string indexhtml {
            get {
                return ResourceManager.GetString("indexhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Kupletsky Sergey on 05.11.14.
        /// *
        /// * Material Design Responsive Table
        /// * Tested on Win8.1 with browsers: Chrome 37, Firefox 32, Opera 25, IE 11, Safari 5.1.7
        /// * You can use this table in Bootstrap (v3) projects. Material Design Responsive Table CSS-style will override basic bootstrap style.
        /// * JS used only for table constructor: you don&apos;t need it in your project
        /// */
        ///
        ///$(document).ready(function() {
        ///
        ///    var table = $(&apos;#table&apos;);
        ///
        ///    // Table bordered
        ///    $(&apos;#table-bordered&apos;).change(function( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string indexjs {
            get {
                return ResourceManager.GetString("indexjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* -- import Roboto Font ---------------------------- */
        ///@import &quot;https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic&amp;subset=latin,cyrillic&quot;;
        ////* -- You can use this tables in Bootstrap (v3) projects. -- */
        ////* -- Box model ------------------------------- */
        ///*,
        ///*:after,
        ///*:before {
        ///  -webkit-box-sizing: border-box;
        ///  -moz-box-sizing: border-box;
        ///  box-sizing: border-box;
        ///}
        ////* -- Demo style ------------------------------- */
        ///html,
        ///bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stylecss {
            get {
                return ResourceManager.GetString("stylecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* -- import Roboto Font ---------------------------- */
        ///@import &quot;https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic&amp;subset=latin,cyrillic&quot;;
        ///
        ////* -- You can use this tables in Bootstrap (v3) projects. -- */
        ///// @import &quot;//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css&quot;;
        ///
        ///
        ////* -- Box model ------------------------------- */
        ///*,
        ///*:after,
        ///*:before {
        ///  -webkit-box-sizing: border-box;
        ///  -moz-box-sizing: border-box;
        ///  box-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styleless {
            get {
                return ResourceManager.GetString("styleless", resourceCulture);
            }
        }
    }
}
